name: client-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Depedencies
              run: yarn

            - name: Run Linter
              run: make lint

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Tests
              run: |
                  make test
                  rm -rf __tests__

            - name: Run Build
              # just to ensure build dont fail due to absence of env variable
              # the real env will be used somewhere else
              env:
                  NODE_ENV: production
                  PUBLIC_URL: publicUrl
                  API: api
                  MAPS_API_KEY: api
                  FIREBASE_API_KEY: api
                  FIREBASE_AUTH_DOMAIN: auth
                  FIREBASE_PROJECT_ID: projectId
                  FIREBASE_STORAGE_BUCKET: bucket
                  FIREBASE_MESSAGING_SENDER_ID: sender
                  FIREBASE_APP_ID: app
                  FIREBASE_MEASUREMENT_ID: measurement
              run: make build
